const missions=[
 {title:'数据训练营',category:'DATA TRAINING',short:'挑选带标签的图片样本，训练小 A。',icon:'⌘',xp:120},
 {title:'机器视觉实验室',category:'COMPUTER VISION',short:'看看遮挡、光线和距离怎样影响 AI。',icon:'◉',xp:140},
 {title:'AI 为什么会犯错',category:'MODEL BIAS',short:'找出模型容易出错的场景，选择补充样本的方法。',icon:'⌁',xp:160},
 {title:'Prompt 魔法学院',category:'PROMPT DESIGN',short:'组合任务、背景、条件和格式卡片。',icon:'✳',xp:160},
 {title:'AI 真假侦探',category:'FACT CHECK',short:'搜集证据，找出 AI 编造的那条情报。',icon:'⌕',xp:180},
 {title:'多模态实验室',category:'MULTIMODAL AI',short:'让文字、图像和声音一起帮助你破案。',icon:'◌',xp:180},
 {title:'AI Agent 行动中心',category:'AI AGENT',short:'给小 A 一个目标，让它规划并调用工具。',icon:'↗',xp:200},
 {title:'拯救未来城',category:'FINAL MISSION',short:'综合运用所学，修复城市 AI 中枢。',icon:'✦',xp:240}
];
const samples=[
 {emoji:'🚁',label:'无人机',type:'drone'}, {emoji:'🐦',label:'小鸟',type:'bird'}, {emoji:'🪁',label:'风筝',type:'kite'}, {emoji:'✈️',label:'飞机',type:'plane'},
 {emoji:'🛸',label:'无人机',type:'drone'}, {emoji:'🐦‍⬛',label:'小鸟',type:'bird'}, {emoji:'🎏',label:'风筝',type:'kite'}, {emoji:'🛩️',label:'飞机',type:'plane'},
 {emoji:'🚁',label:'无人机',type:'drone'}, {emoji:'🐤',label:'小鸟',type:'bird'}, {emoji:'🪁',label:'风筝',type:'kite'}, {emoji:'✈️',label:'飞机',type:'plane'}
];
const tests=[
 {emoji:'🚁',label:'无人机',type:'drone'}, {emoji:'🐦',label:'小鸟',type:'bird'}, {emoji:'🪁',label:'风筝',type:'kite'},
 {emoji:'✈️',label:'飞机',type:'plane'}, {emoji:'🛸',label:'夜间无人机',type:'drone',night:true}, {emoji:'🐤',label:'远处的小鸟',type:'bird',remote:true}
];
const certificateSeries=[
 {heading:'数据训练',title:'数据训练师',copy:'掌握样本筛选、标注与测试的基础方法',tone:'mint'},
 {heading:'机器视觉',title:'视觉观察员',copy:'理解光线、遮挡与距离对识别结果的影响',tone:'violet'},
 {heading:'模型诊断',title:'偏差分析师',copy:'识别数据缺口，并为模型选择改进方向',tone:'amber'},
 {heading:'Prompt 设计',title:'提示词设计师',copy:'能够组合清晰的任务、背景、条件与格式',tone:'mint'},
 {heading:'事实核查',title:'AI 真假侦探',copy:'能够交叉核对证据，识别缺乏依据的回答',tone:'violet'},
 {heading:'多模态协作',title:'多模态侦察员',copy:'能够结合文字、图像和声音分析线索',tone:'amber'},
 {heading:'Agent 规划',title:'Agent 指挥官',copy:'能够拆解目标、调用工具并核实执行结果',tone:'mint'},
 {heading:'未来城守护',title:'未来城守护者',copy:'完成最终综合行动，修复未来城 AI 中枢',tone:'violet'},
 {heading:'AI 特工',title:'高级行动证书',copy:'已完成 AI 特工学院全系列八项行动',tone:'advanced',advanced:true}
];
const agentRanks=['数据学徒','数据训练师','视觉观察员','偏差分析师','提示词设计师','事实核查员','多模态侦察员','Agent 指挥官','未来城守护者'];
const avatarChoices=['🧑‍🚀','👩‍🚀','👨‍🚀','🦊','🐱','🤖','🦄','🦉'];
const defaultState={done:[],xp:0,trust:0,level:1,name:'新晋特工',trained:[],bestAccuracy:0,certDates:{},avatar:'🧑‍🚀'};
let state=loadState(), currentStep=0, selected=new Set(), trainedTypes=new Set(), stage='label', accuracy=0, currentMission=0, currentCertificate=0;
let agentDraft=null;
const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
function photoSrc(item,index=0){
 const night=item.night||false,remote=item.remote||false;
 const sky=night?'#172344':'#82c9ec',ground=night?'#273450':'#d8f1f5';
 let object='';
 if(item.type==='drone') object=`<g transform="translate(80 47) scale(${remote?.62:1})"><path d="M-36 -8h72M-29 10h58" stroke="#273b54" stroke-width="4" stroke-linecap="round"/><rect x="-19" y="-11" width="38" height="19" rx="8" fill="#f3854f" stroke="#963f42" stroke-width="2"/><circle cy="-1" r="7" fill="#69e6dd"/><path d="M-31 -12v-6m31 6v-6m31 6v-6" stroke="#344b60" stroke-width="2"/><path d="M-39 -20h16m46 0h16" stroke="#263e55" stroke-width="3" stroke-linecap="round"/><circle cx="-31" cy="-20" r="4" fill="#d7f6f7"/><circle cx="31" cy="-20" r="4" fill="#d7f6f7"/></g>`;
 else if(item.type==='bird') object=`<g transform="translate(80 50) scale(${remote?.68:1})"><path d="M-25 8Q-35-15-9-20q20-2 24 15l22 9q-15 20-37 13-13-4-25-9z" fill="#ef6290"/><path d="M-12-3q13-23 28-9L4 6" fill="#c63c76"/><circle cx="7" cy="-9" r="2" fill="#fff"/><circle cx="7" cy="-9" r="1" fill="#263349"/><path d="M-2 17l-4 10m14-10 2 10m-19 0h9m5 0h9" stroke="#f4b848" stroke-width="3" stroke-linecap="round"/></g>`;
 else if(item.type==='kite') object=`<g transform="translate(80 39)"><path d="M0-23 25-2 0 18-22-4Z" fill="#ef5576"/><path d="M0-23 0 18 25-2Z" fill="#55d5b3"/><path d="M0-23-22-4 0 18Z" fill="#ffd46c"/><path d="M0 18q12 13-1 23t8 20" fill="none" stroke="#f2f2fa" stroke-width="2"/><path d="m1 30 8 4m-7 9 8 4" stroke="#fd8f74" stroke-width="3"/></g>`;
 else if(item.type==='plane') object=`<g transform="translate(80 47) rotate(-18) scale(${remote?.62:1})"><path d="M-7-34 5-30 10-6 38 8v8L11 9 8 27l10 7v5L1 33-14 38v-5l10-8-3-17-26 8v-8L-7-6Z" fill="#d8e5f3" stroke="#546b96" stroke-width="2"/><path d="m-8-3 18-2M-9 11l18-2" stroke="#899ed0" stroke-width="3"/></g>`;
 const stars=night?`<g fill="#fff4bd"><circle cx="24" cy="19" r="1.3"/><circle cx="131" cy="15" r="1"/><circle cx="115" cy="33" r="1.4"/><circle cx="48" cy="31" r=".9"/></g><circle cx="126" cy="25" r="10" fill="#fff0c3" opacity=".9"/>`:'';
 const smallCloud=`<g fill="#f3fbff" opacity=".72"><path d="M15 72q0-6 7-6 2-9 11-5 7-8 14 1 10-1 10 10z"/><path d="M104 78q0-5 6-5 2-7 9-4 5-7 11 1 8-1 9 8z"/></g>`;
 const occlusion=item.occluded?'<path d="M26 97Q42 60 55 73T82 69Q105 46 120 60T159 54v46H26Z" fill="#375d46" opacity=".9"/><path d="m34 87 24-37m18 45 29-43m15 47 25-39" stroke="#78966a" stroke-width="9" stroke-linecap="round"/>':'';
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 100"><defs><linearGradient id="s" x2="0" y2="1"><stop stop-color="${sky}"/><stop offset="1" stop-color="${ground}"/></linearGradient><linearGradient id="v" x2="0" y2="1"><stop stop-color="#fff" stop-opacity=".12"/><stop offset="1" stop-color="#10243b" stop-opacity=".15"/></linearGradient></defs><rect width="160" height="100" fill="url(#s)"/>${stars}${night?'':smallCloud}<path d="M0 84q37-10 71 1t89-2v17H0z" fill="${night?'#26364c':'#92cdbd'}" opacity=".7"/>${object}${occlusion}<rect width="160" height="100" fill="url(#v)"/></svg>`;
 return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
}
function loadState(){try{const saved=JSON.parse(localStorage.getItem('ai-agent-state')||'{}');return {...defaultState,...saved,certDates:saved.certDates||{},avatar:saved.avatar||defaultState.avatar}}catch{return {...defaultState}}}
function saveState(){localStorage.setItem('ai-agent-state',JSON.stringify(state));renderProgress()}
function showScreen(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));window.scrollTo({top:0,behavior:'smooth'})}
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function agentRank(count){return `LV.${String(Math.min(8,count+1)).padStart(2,'0')} · ${agentRanks[Math.min(8,count)]}`}
function agentTier(count){return count>=8?'master':count>=5?'elite':count>=2?'skilled':'rookie'}
function setAvatar(element,avatar){element.replaceChildren();if(typeof avatar==='string'&&avatar.startsWith('data:image/')){const image=document.createElement('img');image.src=avatar;image.alt='';element.append(image)}else element.textContent=avatarChoices.includes(avatar)?avatar:avatarChoices[0]}
function renderProgress(){let count=state.done.length;$('#progressText').textContent=`${count} / 8`;$('#progressBar').style.width=`${count/8*100}%`,$('#xpCount').textContent=`${state.xp} XP`,$('#trustValue').textContent=state.trust,$('#trustBar').style.width=`${Math.min(state.trust,100)}%`,$('#botLevel').textContent=String(Math.min(8,1+Math.floor(count/1))).padStart(2,'0');$('#agentLevel').textContent=agentRank(count);$('#agentName').textContent=state.name||'新晋特工';$('#profileBtn').dataset.tier=agentTier(count);setAvatar($('#profileAvatar'),state.avatar);let city=Math.min(95,23+count*9);$$('.status-bar i').forEach(e=>e.style.width=`${city}%`);$('#miniCityBar').style.width=`${city}%`;$('#miniCityPct').textContent=`${city}%`;$('#continueLabel').textContent='查看行动地图';$('#companionQuote').innerHTML=count?'和你一起行动真棒！<br>我们继续修复城市。':'我还什么都不会。<br>你愿意训练我吗？';renderMap();$("#firstMissionBtn").innerHTML=count>0&&count<8?"开始下一关 <span>↗</span>":count>=8?"查看行动证书 <span>↗</span>":"开始第一项行动 <span>↗</span>"}
function renderMap(){let root=$('#missionList');if(!root)return;const completed=new Set(state.done),nextIndex=Math.min(state.done.length,missions.length-1);root.innerHTML=missions.map((m,i)=>{let done=completed.has(i),playable=done||i===nextIndex;let status=done?'✓ 已完成':playable?'● 可以开始':'🔒 完成上一关后解锁';return `<article class="mission-card ${done?'done':''} ${playable&&!done?'active-card':''} ${!playable?'locked':''}" data-mission="${i}" aria-label="第${i+1}关：${m.title}，${status}"><div class="card-icon">${m.icon}</div><div><span class="card-num">第 ${String(i+1).padStart(2,'0')} 关</span><h3 class="card-title">${m.title}</h3><div class="card-copy">${m.short}</div></div><span class="card-status">${status}</span>${done?`<button class="card-cert" data-certificate="${i}">查看证书 ↗</button>`:`<span class="card-xp">完成可得 +${m.xp} XP</span>`}</article>`}).join('');$$('.card-cert').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();openCertificate(+button.dataset.certificate)}));$$('.mission-card').forEach(card=>card.addEventListener('click',()=>{const i=+card.dataset.mission;if(!unlockedMission(i)){toast(`请先完成「${missions[i-1]?.title||'上一关'}」，再解锁「${missions[i]?.title}」。`);return}startMission(i)}));}
function unlockedMission(index){return index<state.done.length||index===state.done.length&&index<missions.length}
function goMap(){renderProgress();showScreen('mapScreen')}
$('#startBtn').addEventListener('click',()=>state.done.length?goMap():startMission(0));$('#continueBtn').addEventListener('click',goMap);$('#firstMissionBtn').addEventListener('click',()=>{if(state.done.length<missions.length)startMission(state.done.length);else openCertificate(8)});$('#backMap').addEventListener('click',goMap);$('#resultMapBtn').addEventListener('click',goMap);$('#certMap').addEventListener('click',goMap);
function renderAgentDraft(){if(!agentDraft)return;const preview=$('#agentPreviewAvatar');preview.dataset.tier=agentTier(state.done.length);setAvatar(preview,agentDraft.avatar);$('#agentPreviewName').textContent=$('#agentNameInput').value.trim()||'新晋特工';$('#agentPreviewRank').textContent=agentRank(state.done.length);$('#agentNextRank').textContent=state.done.length>=8?'全部行动完成 · 最高称号已解锁':`完成第 ${state.done.length+1} 关解锁${agentRanks[state.done.length+1]}`;$('#agentAvatarOptions').innerHTML='';avatarChoices.forEach(avatar=>{const button=document.createElement('button');button.type='button';button.className=`agent-avatar-choice ${agentDraft.avatar===avatar?'selected':''}`;button.textContent=avatar;button.setAttribute('aria-label',`选择 ${avatar} 头像`);button.setAttribute('aria-pressed',String(agentDraft.avatar===avatar));button.addEventListener('click',()=>{agentDraft.avatar=avatar;renderAgentDraft()});$('#agentAvatarOptions').append(button)})}
$('#profileBtn').addEventListener('click',()=>{agentDraft={avatar:state.avatar};$('#agentNameInput').value=state.name==='新晋特工'?'':state.name;$('#agentAvatarFile').value='';renderAgentDraft();$('#agentDialog').showModal()});
$('#agentNameInput').addEventListener('input',renderAgentDraft);
$('#agentClose').addEventListener('click',()=>$('#agentDialog').close());
$('#agentCancel').addEventListener('click',()=>$('#agentDialog').close());
$('#agentDialog').addEventListener('click',event=>{if(event.target===$('#agentDialog'))$('#agentDialog').close()});
$('#agentDialog').addEventListener('close',()=>{agentDraft=null});
$('#agentAvatarFile').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)||file.size>10*1024*1024){toast('请选择不超过 10 MB 的图片。');return}const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=160;canvas.height=160;const context=canvas.getContext('2d');const side=Math.min(image.naturalWidth,image.naturalHeight);context.drawImage(image,(image.naturalWidth-side)/2,(image.naturalHeight-side)/2,side,side,0,0,160,160);if(agentDraft){agentDraft.avatar=canvas.toDataURL('image/jpeg',.82);renderAgentDraft()}}catch{toast('图片读取失败，请换一张试试。')}finally{URL.revokeObjectURL(url)}});
$('#agentSave').addEventListener('click',()=>{if(!agentDraft)return;state.name=$('#agentNameInput').value.trim().slice(0,12)||'新晋特工';state.avatar=agentDraft.avatar;try{saveState()}catch{toast('无法保存头像，请尝试更小的图片。');return}$('#agentDialog').close();toast('特工角色已保存！')});
function startMission(index){if(!unlockedMission(index)){toast('请先完成前一关，再来这里行动。');return}if(index===1){startVisionMission();return}if(index===2){startBiasMission();return}if(index>=3){startExtraMission(index);return}currentMission=index;currentStep=0;selected=new Set();trainedTypes=new Set();stage='label';accuracy=0;$('#feedback').textContent='';$('#missionIndex').textContent=String(index+1).padStart(2,'0');$('#missionCategory').textContent=missions[index].category;$('#missionTitle').textContent='教小 A 认识天空中的物体';$('#missionDesc').textContent='城市监控把无人机、鸟、风筝和飞机混在了一起。选择至少 4 张已标注图片，其中要有无人机，再用新图片检查小 A 是否学会了这些类别。';$('#missionCrumb').textContent=`${String(index+1).padStart(2,'0')} ${missions[index].title}`;$('#hintText').textContent='第 1 步：选至少 4 张图片，并确保其中有一张无人机。点击卡片可选择或取消。';$('#asideChat').textContent='“请给我一些例子，我会从中学习怎么分辨无人机。”';$('#conceptCopy').textContent='本测试版用简化规则模拟训练：小 A 只能识别你选中的图片类别。测试环节会用新图片检查结果。';renderStep();showScreen('missionScreen')}
function renderStep(){let dots=Array.from({length:4},(_,i)=>`<i class="${i<=currentStep?'done':''}"></i>`).join('');$('#stepDots').innerHTML=dots;$('#stepLabel').textContent=`0${currentStep+1} / 04`;if(currentStep===0)renderLabelStep();if(currentStep===1)renderTrainingStep();if(currentStep===2)renderTestStep();if(currentStep===3)renderLearnStep()}
function renderLabelStep(){stage='label';selected.clear();$('#actionBtn').disabled=true;$('#actionBtn').innerHTML='至少选 4 张，含无人机';$('#hintText').textContent='第 1 步 / 选样本：至少选择 4 张图片，其中包含 1 张无人机。';$('#playArea').innerHTML=`<div class="area-head"><span>✦&nbsp; 训练图片 / 小 A 将从这些例子学习</span><span class="sample-counter"><b id="selectedCount">0</b> / 12 已选择</span></div><div class="step-instruction"><b>你的任务</b><span>选至少 4 张无人机、鸟、风筝或飞机的图片，并至少选 1 张无人机。类别标签已标在每张图片下方。</span></div><div class="samples">${samples.map((x,i)=>`<button class="sample" data-sample="${i}" aria-pressed="false" aria-label="训练图片：${x.label}，${selected.has(i)?'已选择':'点击加入训练'}"><img class="sample-photo" src="${photoSrc(x,i)}" alt="${x.label}图片"><span>${x.label}</span></button>`).join('')}</div>`;$$('.sample').forEach(el=>el.addEventListener('click',()=>{let i=+el.dataset.sample;if(selected.has(i)){selected.delete(i);el.classList.remove('selected');el.setAttribute('aria-pressed','false')}else{selected.add(i);el.classList.add('selected');el.setAttribute('aria-pressed','true')}const hasDrone=[...selected].some(n=>samples[n].type==='drone'),ready=selected.size>=4&&hasDrone;$('#selectedCount').textContent=selected.size;$('#actionBtn').disabled=!ready;$('#actionBtn').innerHTML=ready?'开始训练小 A':selected.size<4?`还要选 ${4-selected.size} 张`:'还要选 1 张无人机';$('#hintText').textContent=selected.size<4?`已选 ${selected.size} 张，还需 ${4-selected.size} 张。`:`${hasDrone?'已包含无人机样本。':'还需选择至少 1 张无人机。'}${ready?'可以开始训练小 A。':''}`}))}
function renderTrainingStep(){stage='training';trainedTypes=new Set([...selected].map(i=>samples[i].type));$('#actionBtn').disabled=true;$('#actionBtn').innerHTML='小 A 正在训练…';$('#hintText').textContent='第 2 步 / 训练中：观察小 A 如何从已标注图片中学习。';$('#asideChat').textContent='“我正在比较图片里的样子，寻找能分辨无人机的规律。”';$('#conceptCopy').textContent=`已选择 ${selected.size} 张训练图片，包含：${[...trainedTypes].map(t=>({drone:'无人机',bird:'小鸟',kite:'风筝',plane:'飞机'}[t])).join('、')}。模型只能学到训练样本中出现的类别。`;
 $('#playArea').innerHTML=`<div class="area-head"><span>✦&nbsp; 小 A 正在学习</span><span class="sample-counter">TRAINING IN PROGRESS</span></div><div class="training-status" style="margin-top:28px;padding:19px"><div class="training-top"><span id="trainingLabel"><i></i> 正在整理样本</span><span class="mono" id="trainingPercent">0%</span></div><div class="training-bar"><i id="trainingBar"></i></div><div class="training-log" id="trainingLog">收集到 ${selected.size} 条标注线索…</div></div><div class="play-reveal" style="margin-top:19px"><div class="reveal-label">MODEL IN TRAINING</div><div class="reveal-copy">AI 不会一出生就认识世界。它通过大量带有正确答案的例子，慢慢学会数据和答案之间的规律。</div></div>`;
 const logs=['收集并整理已标注样本…','正在比较图片之间的特征…','小 A 正在建立识别规律…','检查模型表现…'];let n=0;const timer=setInterval(()=>{n++;let p=Math.min(100,n*25);$('#trainingBar').style.width=`${p}%`;$('#trainingPercent').textContent=`${p}%`;$('#trainingLog').textContent=logs[Math.min(n-1,3)];if(n===4){clearInterval(timer);stage='trained';$('#trainingLabel').classList.add('training-running');$('#trainingLabel').innerHTML='<i></i> 训练完成';$('#actionBtn').disabled=false;$('#actionBtn').innerHTML='测试小 A <span class="btn-arrow">↗</span>';$('#feedback').textContent='训练完成！接下来用小 A 没见过的新图片测试一下。';$('#asideChat').textContent='“我好像学会了一些规律！来考考我吧。”';}},520)}
function renderTestStep(){stage='test';$('#actionBtn').disabled=true;$('#actionBtn').innerHTML='先检查 6 张图片';$('#hintText').textContent='第 3 步 / 测试：逐张查看小 A 对新图片的判断。';$('#asideChat').textContent='“这些新图片我没见过。让我试着分辨它们！”';$('#conceptCopy').textContent='本测试版用简化规则模拟分类：小 A 只会认出训练样本中出现过的类别。';$('#playArea').innerHTML=`<div class="area-head"><span>✦&nbsp; 新图片 / 检查小 A 是否学会了</span><span class="sample-counter"><b id="testCount">0</b> / 6 已检查</span></div><div class="step-instruction"><b>你的任务</b><span>逐张点击图片，查看小 A 是否认对类别。留意夜间无人机和远处的小鸟，它们与训练图片不同。</span></div><div class="test-cards">${tests.map((x,i)=>`<button class="test-card" data-test="${i}" aria-label="新图片：${x.label}。点击查看小 A 的判断"><img class="test-photo" src="${photoSrc(x,i)}" alt="${x.label}"><span>${x.label}</span><span class="test-answer" aria-live="polite"></span></button>`).join('')}</div><div id="testResult"></div>`;let answered=new Set(),correct=0;$$('.test-card').forEach(el=>el.addEventListener('click',()=>{const i=+el.dataset.test;if(answered.has(i))return;answered.add(i);const item=tests[i],learned=trainedTypes.has(item.type),isCorrect=item.type==='drone';
 const success=learned;el.classList.add(success?'correct':'wrong');el.classList.add('disabled');el.querySelector('.test-answer').textContent=success?`小 A：识别为${{drone:'无人机',bird:'小鸟',kite:'风筝',plane:'飞机'}[item.type]} ✓`:'小 A：还不认识这个类别 ✕';if(success)correct++;else $('#feedback').textContent=`小 A 没有学过“${{drone:'无人机',bird:'小鸟',kite:'风筝',plane:'飞机'}[item.type]}”类别。训练样本要尽量包含你希望它认识的各类图片。`;$('#asideChat').textContent=success?'“我认出来啦！这些训练样本帮了我大忙。”':'“这类图片我还没学过。下次记得也给我看一些例子！”';$('#testCount').textContent=answered.size;if(answered.size===tests.length){accuracy=Math.round(correct/tests.length*100);$('#testResult').innerHTML=`<div class="play-reveal"><div class="reveal-label">测试结果 / 新图片分类准确率</div><div class="reveal-score">${accuracy}% <span style="font-size:12px;color:#b6c5d7">${correct} / 6 张判断正确</span></div><div class="reveal-copy">小 A 在 6 张训练外的新图片中判断正确 ${correct} 张。${accuracy<100?'遗漏的类别没有出现在训练样本里。给模型更多不同类别的例子，再测试一次吧。':'太棒了！你的样本包含了多种类别，小 A 成功认出了这些新图片。点击下方查看本关行动报告。'}</div><button class="btn-primary reveal-continue" id="toLearn">查看行动报告 <span class="btn-arrow">↗</span></button></div>`;$('#actionBtn').disabled=true;$('#actionBtn').style.display='none';$('#toLearn').addEventListener('click',()=>{currentStep=3;renderStep();$('#feedback').textContent='';$('#actionBtn').style.display='inline-flex'})}}))}
function renderLearnStep(){stage='learn';$('#hintText').textContent='第一项行动完成！带着新发现继续探索未来城。';$('#asideChat').textContent='“我学会了！原来我需要你提供好的例子。”';$('#conceptCopy').textContent='数据不会自动变成智能。AI 从带标签的样本中找规律，再用学到的规律判断新图片。';$('#actionBtn').innerHTML='领取行动奖励 <span class="btn-arrow">↗</span>';$('#actionBtn').disabled=false;$('#playArea').innerHTML=`<div class="area-head"><span>✦&nbsp; 行动报告 / FIELD REPORT</span><span class="sample-counter">MISSION 01</span></div><div class="play-reveal" style="margin-top:22px;padding:20px"><div class="reveal-label">你刚刚完成了</div><div class="reveal-copy" style="font-size:12px;margin-top:9px">挑选带标签的样本 → 用这些例子训练小 A → 用没见过的新图片测试。<br><br>AI 不会天生聪明。<strong style="color:#e5f2ff">它从数据里学习规律</strong>，而数据能不能代表真实世界，会影响它的表现。</div></div><div class="training-status"><div class="training-top"><span>本次测试准确率</span><span style="color:var(--mint);font-family:var(--mono)">${accuracy}%</span></div><div class="training-bar"><i style="width:${accuracy}%"></i></div><div class="training-log">已完成：样本筛选 · 模拟训练 · 新图片测试</div></div>`}
$('#actionBtn').addEventListener('click',()=>{if(stage==='label'){if(selected.size<4||![...selected].some(i=>samples[i].type==='drone')){toast('至少选择 4 张图片，并包含 1 张无人机。');return}currentStep=1;renderStep();$('#feedback').textContent='';return}if(stage==='training'){toast('小 A 还在学习，请等一会儿。');return}if(stage==='trained'){currentStep=2;renderStep();$('#feedback').textContent='';return}if(stage==='learn')completeMission();if(stage==='vision'&&document.querySelectorAll('.vision-card.checked').length===4)completeVisionMission();if(stage==='bias'&&document.querySelectorAll('.bias-card.checked').length===4&&document.querySelector('.bias-fix-choice.selected.correct'))completeBiasMission();if(stage==='extra')advanceExtraMission()});
function completeMission(){if(!state.done.includes(currentMission)){state.done.push(currentMission);state.certDates[currentMission]=new Date().toLocaleDateString('zh-CN');let earned=missions[currentMission].xp;state.xp+=earned;state.trust=Math.min(100,state.trust+18);state.bestAccuracy=Math.max(state.bestAccuracy,accuracy);state.trained=Array.from(trainedTypes);saveState()}$('#resultTitle').textContent=accuracy>=100?'小 A 学会了新本领！':'第一步，训练完成。';$('#resultCopy').textContent=accuracy>=100?'小 A 成功认出了无人机。你们一起迈出了修复未来城的第一步。':'你和小 A 找到了改进方向。未来城正在恢复。';$('#resultXP').textContent=`+${missions[currentMission].xp} XP`;$('#resultSkill').textContent='样本筛选';$('#resultCity').textContent='+9%';$('#nextBtn').innerHTML='领取本关证书 <span class="btn-arrow">↗</span>';confetti();showScreen('resultScreen')}
function confetti(){const c=$('#confetti');c.innerHTML=Array.from({length:32},(_,i)=>`<i class="confetti-bit" style="left:${Math.random()*100}%;animation-delay:${Math.random()*1.3}s;animation-duration:${2+Math.random()*2}s"></i>`).join('')}
function openCertificate(index){const unlocked=index<8?state.done.includes(index):state.done.length>=8;if(!unlocked){toast('完成对应行动后即可解锁这张证书。');return}currentCertificate=index;const cert=certificateSeries[index],isAdvanced=!!cert.advanced;$('#certificateCard').className=`certificate cert-${cert.tone}`;$('#certEyebrow').textContent=isAdvanced?'MASTER CERTIFICATE · COMPLETE SERIES':`MISSION ${String(index+1).padStart(2,'0')} · CERTIFICATE`;$('#certHeading').innerHTML=`${cert.heading}<br><span>${isAdvanced?'高级证书':'行动证书'}</span>`;$('#certCopy').innerHTML=isAdvanced?`${cert.copy}，<br>获授 AI 特工学院最高行动等级。`:`已成功完成「${missions[index].title}」行动，<br>${cert.copy}。`;$('#certRank').textContent=`✦ ${cert.title} · ${isAdvanced?'MASTER':'LV.'+String(index+1).padStart(2,'0')} ✦`;$('#certStamp').innerHTML=isAdvanced?'AI<br>MASTER':`AI<br>LV.${String(index+1).padStart(2,'0')}`;$('#certDate').textContent=state.certDates?.[index]||state.certDates?.[7]||new Date().toLocaleDateString('zh-CN');$('#certNumber').textContent=`FC-2035-${isAdvanced?'MASTER':String(index+1).padStart(2,'0')}`;$('#certName').value=state.name==='新晋特工'?'':state.name;$('#certSeriesTitle').textContent=`行动证书系列 · ${String(index+1).padStart(2,'0')} / 09`;$('#certSeriesBar').style.width=`${Math.min(9,state.done.length+(state.done.length>=8?1:0))/9*100}%`;$('#certificateCollection').innerHTML=certificateSeries.map((item,i)=>{const available=i<8?state.done.includes(i):state.done.length>=8;return `<button class="cert-mini ${available?'unlocked':'locked'} ${i===index?'selected':''} ${item.advanced?'advanced':''}" data-cert="${i}" ${available?'':'disabled'}><span>${item.advanced?'✦':String(i+1).padStart(2,'0')}</span><b>${item.title}</b><small>${available?'已获得':'未解锁'}</small></button>`}).join('');$$('.cert-mini.unlocked').forEach(button=>button.addEventListener('click',()=>openCertificate(+button.dataset.cert)));$('#nextCert').hidden=!(index===7&&state.done.length>=8);showScreen('certificateScreen')}
$('#nextBtn').addEventListener('click',()=>openCertificate(currentMission));
$('#nextCert').addEventListener('click',()=>openCertificate(8));
$('#saveCert').addEventListener('click',()=>{const name=$('#certName').value.trim();if(name){state.name=name.slice(0,12);saveState()}window.print()});$('#certName').addEventListener('input',e=>{state.name=e.target.value;$('#agentName').textContent=state.name||'新晋特工'});
function updateClock(){const now=new Date();const h=String((now.getHours()+20)%24).padStart(2,'0');const m=String(now.getMinutes()).padStart(2,'0');const s=String(now.getSeconds()).padStart(2,'0');$('#clock').textContent=`${h}:${m}:${s}`}
updateClock();setInterval(updateClock,1000);renderProgress();if(location.hash==='#map')goMap();


